service: my-lamdba-based-application

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  echo:
    handler: handler.index
    events:
      - http: 
          path: hello
          method: get
          cors: true
  getOrCreateUser:
    handler: handler.getOrCreateUser
    events:
      - http: 
          path: getorcreate
          method: post
          cors: true